#! /bin/sh

# Restore wallpaper
bash $HOME/.config/scripts/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &
# $HOME/.config/polybar/launch.sh # by me

# workspaces() {
# 	name=1
# 	for monitor in `bspc query -M`; do
# 		# bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' '' '漣'
# 		# bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '0'
# 		bspc monitor ${monitor} -n "$name" -d 'DEV' 'WWA' 'SYS' 'WWB' 'COD' 'API' 'DB' 'VIR' 'DIS' 'MUS'
# 		let name++
# 	done
# }
# workspaces

# bspc monitor DP-2 -d XXI XII III XIV XXV XVI VII VIII XIX XXX
# bspc monitor HDMI-2 -d  Dev WWA SYS WWB COD DIS SPO
#
bspc monitor DP-2 -d XXI XII III XIV
bspc monitor HDMI-2 -d XXV XVI VII VIII XIX XXX


bspc config border_width         2

bspc config window_gap           5
bspc config split_ratio          0.50

# bspc monitor DP-2 -d 1 2 3 4 5
# bspc monitor HDMI-1 -d 6 7 8 9 0

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

#  --------->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> me

# # workspace 1 (Terminals)
# declare -a terminal=(Alacritty Xfce4-terminal)
# for i in ${terminal[@]}; do
#     bspc rule -a $i desktop='^1' follow=on focus=on; done

# # workspace 2 (Internet Browser)
# declare -a web=(firefox discord)
# for i in ${web[@]}; do
#     bspc rule -a $i desktop='^2' follow=on focus=on; done

# # workspace 3 (Files)
# declare -a filem=(Thunar Pcmanfm qBittorrent)
# for i in ${filem[@]}; do
#     bspc rule -a $i desktop='^3' follow=on focus=on; done

# # workspace 4 (Text Editor)
# declare -a office=(Code Geany)
# for i in ${office[@]}; do
#     bspc rule -a $i desktop='^4' follow=on focus=on; done

# # workspace 5 (Media)
# declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
# "VirtualBox Manager")
# for i in ${media[@]}; do
#     bspc rule -a $i desktop='^5' follow=on focus=on; done

# # workspace 7 (Settings)
# declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
# Pavucontrol Xfce4-settings-manager)
# for i in ${settings[@]}; do
#     bspc rule -a $i desktop='^7' follow=on focus=on; done

declare -a settings=(discord)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^9' follow=off focus=off; done

declare -a settings=(easyeffects)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^10' follow=off focus=off; done

declare -a settings=(Spotify)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^10' follow=off focus=off; done


# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad Rider)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

#  --------->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> me

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar top_primary &
polybar top_secondary &

dunst -config $HOME/.config/dunst/dunstrc-bspwm &
sxhkd &
xfce4-power-manager &
# easyeffects&
# discord&

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/picom/picom.conf &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi


# replace neovim colorscheme
# sed -i "s/theme =.*$/theme = \"tokyonight\",/g" $HOME/.config/nvim/lua/custom/chadrc.lua
# change xfce4-terminal colorscheme

XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc

# change cava colorscheme
CAVA_PATH="$HOME/.config/cava"
cp "$CAVA_PATH"/colorschemes/tokyo-night "$CAVA_PATH"/config
