import = [
  "~/.config/alacritty/keybindings/keybindings.toml",

  #### selected theme ###

  # "~/.config/alacritty/themes/custom-one.toml",
  # "~/.config/alacritty/themes/custom-two.toml",
  # "~/.config/alacritty/themes/alacritty-theme/themes/github_dark.toml",
  # "~/.config/alacritty/themes/alacritty-theme/themes/gruvbox_material_hard_dark.toml",
  # "~/.config/alacritty/themes/alacritty-theme/themes/tokyo-night.toml",
  # "~/.config/alacritty/themes/alacritty-theme/themes/github_dark_high_contrast.toml",
  "~/.config/alacritty/themes/alacritty-theme/themes/alabaster_dark.toml",

  ### selected font ### 

  # "~/.config/alacritty/fonts/source-code.toml",
  # "~/.config/alacritty/fonts/fira.toml",
  # "~/.config/alacritty/fonts/hack.toml",
  # "~/.config/alacritty/fonts/jetbrains-font.toml",
  "~/.config/alacritty/fonts/ibm-blex.toml",
]

[bell]
animation = "EaseOutExpo"
duration = 1

[font] # here only the font size is set
size = 10.0

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
# TERM = "alacritty"

[scrolling]
history = 5000

[window]
decorations = "full"
title = "Alacritty"
dynamic_title = true
dynamic_padding = false
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
