import = [
  "~/.config/alacritty/themes/custom-one.toml",
  "~/.config/alacritty/keybindings/keybindings.toml",
  "~/.config/alacritty/fonts/jetbrains-font.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 1

[font] # here only the font size is set
size = 10.0

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"
# TERM = "alacritty"

[scrolling]
history = 5000

[window]
decorations = "full"
title = "Alacritty"
dynamic_title = true
dynamic_padding = false
opacity = 1.0

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
